# Generated by Django 5.2.8 on 2025-11-29 07:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام دوربین')),
                ('location', models.CharField(max_length=200, verbose_name='موقعیت')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال'), ('maintenance', 'در حال تعمیر')], default='active', max_length=20)),
                ('ip_address', models.GenericIPAddressField(verbose_name='آدرس IP')),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('efficiency', models.FloatField(default=0.0, verbose_name='بازدهی')),
            ],
            options={
                'verbose_name': 'دوربین',
                'verbose_name_plural': 'دوربین\u200cها',
            },
        ),
        migrations.CreateModel(
            name='ConveyorBelt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام نوار نقاله')),
                ('status', models.CharField(choices=[('operational', 'عملیاتی'), ('maintenance', 'تعمیرات'), ('stopped', 'متوقف شده')], default='operational', max_length=20)),
                ('current_speed', models.FloatField(default=0.0, verbose_name='سرعت فعلی')),
                ('average_efficiency', models.FloatField(default=0.0, verbose_name='میانگین بازدهی')),
                ('last_maintenance', models.DateField(blank=True, null=True, verbose_name='آخرین تعمیر')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.camera', verbose_name='دوربین')),
            ],
            options={
                'verbose_name': 'نوار نقاله',
                'verbose_name_plural': 'نوارهای نقاله',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('overload', 'بار بیش از حد'), ('misalignment', 'انحراف نوار'), ('imbalance', 'عدم تعادل بار'), ('jam', 'گیر کردن'), ('maintenance', 'نیاز به تعمیر')], max_length=20, verbose_name='نوع هشدار')),
                ('severity', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'بالا'), ('critical', 'بحرانی')], max_length=20, verbose_name='شدت')),
                ('message', models.TextField(verbose_name='پیام')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان')),
                ('resolved', models.BooleanField(default=False, verbose_name='حل شده')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان حل')),
                ('conveyor_belt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.conveyorbelt', verbose_name='نوار نقاله')),
            ],
            options={
                'verbose_name': 'هشدار',
                'verbose_name_plural': 'هشدارها',
                'ordering': ['-timestamp'],
            },
        ),
    ]
