# Generated by Django 5.2.8 on 2025-11-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conveyorbelt',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='conveyor_videos/', verbose_name='فیلم نوار نقاله'),
        ),
        migrations.AddField(
            model_name='conveyorbelt',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='آدرس فیلم'),
        ),
    ]
