# Generated by Django 5.2.8 on 2025-11-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_conveyorbelt_video_conveyorbelt_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP'),
        ),
    ]
