# Generated by Django 5.2.8 on 2025-11-30 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0003_camera_port_alter_camera_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conveyorbelt',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='camera.camera', verbose_name='دوربین'),
        ),
    ]
