# Generated by Django 5.2.8 on 2025-11-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0004_alter_conveyorbelt_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
