# Generated by Django 5.2.8 on 2025-12-02 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0005_camera_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='conveyorbelt',
            name='plc_logic',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='PLC Logic JSON'),
        ),
        migrations.AddField(
            model_name='conveyorbelt',
            name='style',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Style JSON'),
        ),
    ]
