# Generated by Django 5.2.9 on 2025-12-07 08:14

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detection',
            options={'ordering': ['frame_number']},
        ),
        migrations.AlterModelOptions(
            name='processingjob',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='detection',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='videofile',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='detection',
            name='is_iron_ore',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detection',
            name='object_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detection',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videofile',
            name='filename',
            field=models.CharField(default=datetime.datetime(2025, 12, 7, 8, 14, 33, 813698, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videofile',
            name='size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detection',
            name='bbox',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='detection',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='detection',
            name='frame_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detection',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='vision.processingjob'),
        ),
        migrations.AlterField(
            model_name='detection',
            name='label',
            field=models.CharField(default='object', max_length=50),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='camera_id',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='job_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='progress',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error'), ('stopped', 'Stopped')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='vision.videofile'),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='path',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='BeltMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, max_length=100)),
                ('frame_number', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('speed', models.FloatField(default=0.0)),
                ('avg_speed', models.FloatField(default=0.0)),
                ('vibration_amplitude', models.FloatField(default=0.0)),
                ('vibration_frequency', models.FloatField(default=0.0)),
                ('vibration_severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=10)),
                ('alignment_deviation', models.IntegerField(default=0)),
                ('avg_alignment', models.FloatField(default=0.0)),
                ('belt_width', models.FloatField(default=0.0)),
                ('belt_found', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['frame_number'],
                'indexes': [models.Index(fields=['job_id', 'frame_number'], name='vision_belt_job_id_de4944_idx')],
            },
        ),
    ]
