# Generated by Django 5.2.9 on 2025-12-07 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0002_alter_detection_options_alter_processingjob_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BeltMetrics',
        ),
        migrations.DeleteModel(
            name='Detection',
        ),
    ]
