# Generated by Django 5.2.9 on 2025-12-09 08:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0003_delete_beltmetrics_delete_detection'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('camera_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.CharField(blank=True, max_length=50)),
                ('port', models.IntegerField(default=554)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('target_fps', models.FloatField(default=15.0)),
                ('resolution_width', models.IntegerField(default=1920)),
                ('resolution_height', models.IntegerField(default=1080)),
                ('roi_x1', models.FloatField(default=0.1)),
                ('roi_y1', models.FloatField(default=0.15)),
                ('roi_x2', models.FloatField(default=0.9)),
                ('roi_y2', models.FloatField(default=0.85)),
                ('belt_width_mm', models.FloatField(default=1000.0)),
                ('belt_length_m', models.FloatField(default=50.0)),
                ('max_speed_mps', models.FloatField(default=5.0)),
                ('enabled', models.BooleanField(default=True)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'camera_configurations',
            },
        ),
        migrations.RenameField(
            model_name='videofile',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.AddField(
            model_name='processingjob',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='camera_id',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='job_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vision.videofile'),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='processingjob',
            table='processing_jobs',
        ),
        migrations.AlterModelTable(
            name='videofile',
            table='video_files',
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('spillage', 'Material Spillage'), ('edge_damage', 'Edge Damage'), ('alignment', 'Belt Misalignment'), ('speed', 'Speed Anomaly'), ('vibration', 'Excessive Vibration'), ('system', 'System Alert')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, null=True)),
                ('camera_id', models.CharField(default='unknown', max_length=50)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_by', models.CharField(blank=True, max_length=100, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='vision.processingjob')),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AlertConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('camera_id', models.CharField(max_length=50)),
                ('alert_type', models.CharField(choices=[('spillage', 'Material Spillage'), ('edge_damage', 'Edge Damage'), ('alignment', 'Belt Misalignment'), ('speed', 'Speed Anomaly'), ('vibration', 'Excessive Vibration'), ('system', 'System Alert')], max_length=20)),
                ('warning_threshold', models.FloatField()),
                ('critical_threshold', models.FloatField()),
                ('min_duration_frames', models.IntegerField(default=5)),
                ('alert_cooldown_seconds', models.IntegerField(default=30)),
                ('send_email', models.BooleanField(default=False)),
                ('send_sms', models.BooleanField(default=False)),
                ('play_sound', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'alert_configurations',
                'unique_together': {('camera_id', 'alert_type')},
            },
        ),
        migrations.CreateModel(
            name='BeltCalibration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('camera_id', models.CharField(max_length=50)),
                ('reference_width_mm', models.FloatField()),
                ('reference_height_mm', models.FloatField()),
                ('pixels_per_mm', models.FloatField()),
                ('belt_width_pixels', models.FloatField()),
                ('belt_height_pixels', models.FloatField()),
                ('calibration_frame', models.TextField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibrations', to='vision.processingjob')),
            ],
            options={
                'db_table': 'belt_calibrations',
            },
        ),
        migrations.CreateModel(
            name='ReplayBuffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frames', models.JSONField()),
                ('timestamps', models.JSONField()),
                ('metrics', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='replay_buffer', to='vision.processingjob')),
            ],
            options={
                'db_table': 'replay_buffers',
            },
        ),
        migrations.CreateModel(
            name='BeltMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('frame_number', models.IntegerField()),
                ('belt_found', models.BooleanField()),
                ('speed_kmh', models.FloatField()),
                ('alignment_deviation', models.FloatField()),
                ('belt_area_pixels', models.FloatField()),
                ('spillage_area', models.FloatField(default=0.0)),
                ('spill_count', models.IntegerField(default=0)),
                ('edge_damages', models.IntegerField(default=0)),
                ('edge_severity', models.CharField(default='none', max_length=20)),
                ('vibration_amplitude', models.FloatField(default=0.0)),
                ('vibration_frequency', models.FloatField(default=0.0)),
                ('vibration_severity', models.CharField(default='none', max_length=20)),
                ('belt_confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='vision.processingjob')),
            ],
            options={
                'db_table': 'belt_metrics',
                'indexes': [models.Index(fields=['job', 'timestamp'], name='belt_metric_job_id_e0a723_idx'), models.Index(fields=['timestamp'], name='belt_metric_timesta_da7c2a_idx')],
            },
        ),
    ]
