# Generated by Django 5.2.9 on 2025-12-09 09:00

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0004_cameraconfiguration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeltProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('profile_type', models.CharField(choices=[('default', 'Default'), ('custom', 'Custom'), ('calibrated', 'Calibrated')], default='custom', max_length=20)),
                ('belt_width_mm', models.FloatField(default=1000, help_text='Belt width in millimeters')),
                ('belt_length_m', models.FloatField(default=0, help_text='Belt length in meters')),
                ('belt_speed_min', models.FloatField(default=0.5, help_text='Minimum operating speed (m/s)')),
                ('belt_speed_max', models.FloatField(default=5.0, help_text='Maximum operating speed (m/s)')),
                ('material_type', models.CharField(choices=[('pellets', 'Pellets'), ('gravel', 'Gravel'), ('sand', 'Sand'), ('coal', 'Coal'), ('ore', 'Ore'), ('grain', 'Grain'), ('other', 'Other')], default='other', max_length=20)),
                ('detection_params', models.JSONField(default=dict, help_text='Belt detection parameters')),
                ('alert_thresholds', models.JSONField(default=dict, help_text='Alert thresholds for this belt')),
                ('calibration_data', models.JSONField(blank=True, help_text='Calibration data', null=True)),
                ('pixels_per_mm', models.FloatField(default=1.0, help_text='Calibration: pixels per millimeter')),
                ('calibration_image', models.TextField(blank=True, help_text='Base64 encoded calibration image')),
                ('reference_images', models.JSONField(blank=True, default=list, help_text='List of reference image paths')),
                ('camera_id', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Belt Profile',
                'verbose_name_plural': 'Belt Profiles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frame_number', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('belt_found', models.BooleanField(default=False)),
                ('speed', models.FloatField(default=0, help_text='Belt speed in km/h')),
                ('alignment_deviation', models.FloatField(default=0, help_text='Alignment deviation in pixels')),
                ('belt_area', models.FloatField(default=0, help_text='Belt area in pixels')),
                ('spillage_area', models.FloatField(default=0, help_text='Spillage area in pixels')),
                ('spill_count', models.IntegerField(default=0)),
                ('edge_damage_count', models.IntegerField(default=0)),
                ('edge_damage_severity', models.CharField(default='none', max_length=10)),
                ('belt_confidence', models.FloatField(default=0, help_text='Belt detection confidence (0-1)')),
                ('detection_confidence', models.FloatField(default=0, help_text='Overall detection confidence')),
                ('has_spillage_alert', models.BooleanField(default=False)),
                ('has_edge_damage_alert', models.BooleanField(default=False)),
                ('has_alignment_alert', models.BooleanField(default=False)),
                ('snapshot', models.TextField(blank=True, help_text='Base64 encoded frame snapshot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Processing History',
                'verbose_name_plural': 'Processing History',
                'ordering': ['job', 'frame_number'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('config_type', models.CharField(choices=[('detection', 'Detection'), ('alerting', 'Alerting'), ('processing', 'Processing'), ('system', 'System'), ('ui', 'UI')], max_length=20)),
                ('value', models.JSONField(help_text='Configuration value (JSON)')),
                ('is_active', models.BooleanField(default=True)),
                ('is_editable', models.BooleanField(default=True, help_text='Can be edited via UI')),
                ('requires_restart', models.BooleanField(default=False, help_text='Requires system restart')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configurations',
                'ordering': ['config_type', 'key'],
            },
        ),
        migrations.DeleteModel(
            name='AlertConfiguration',
        ),
        migrations.RemoveField(
            model_name='beltcalibration',
            name='job',
        ),
        migrations.RemoveField(
            model_name='beltmetrics',
            name='job',
        ),
        migrations.DeleteModel(
            name='CameraConfiguration',
        ),
        migrations.RemoveField(
            model_name='replaybuffer',
            name='job',
        ),
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-timestamp', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='processingjob',
            options={'ordering': ['-created_at'], 'verbose_name': 'Processing Job', 'verbose_name_plural': 'Processing Jobs'},
        ),
        migrations.AlterModelOptions(
            name='videofile',
            options={'ordering': ['-recorded_at', '-created_at']},
        ),
        migrations.RenameField(
            model_name='videofile',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='acknowledged',
        ),
        migrations.RemoveField(
            model_name='processingjob',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='processingjob',
            name='started_at',
        ),
        migrations.AddField(
            model_name='alert',
            name='duration',
            field=models.FloatField(default=0, help_text='Alert duration in seconds'),
        ),
        migrations.AddField(
            model_name='alert',
            name='frame_number',
            field=models.IntegerField(blank=True, help_text='Frame where alert occurred', null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='resolution_notes',
            field=models.TextField(blank=True, help_text='Notes on how alert was resolved'),
        ),
        migrations.AddField(
            model_name='alert',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='resolved_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='alert',
            name='snapshot',
            field=models.TextField(blank=True, help_text='Base64 encoded snapshot of the alert'),
        ),
        migrations.AddField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='alert',
            name='thumbnail',
            field=models.TextField(blank=True, help_text='Base64 encoded thumbnail'),
        ),
        migrations.AddField(
            model_name='alert',
            name='title',
            field=models.CharField(default=datetime.datetime(2025, 12, 9, 9, 0, 6, 746641, tzinfo=datetime.timezone.utc), help_text='Short alert title', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='alerts_summary',
            field=models.JSONField(blank=True, default=dict, help_text='Summary of alerts generated'),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='calibration_data',
            field=models.JSONField(blank=True, help_text='Calibration data', null=True),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='created_by',
            field=models.CharField(blank=True, help_text='Who created the job', max_length=100),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='current_frame',
            field=models.IntegerField(default=0, help_text='Current frame being processed'),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='detection_params',
            field=models.JSONField(blank=True, default=dict, help_text='Detection parameters used'),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='When processing ended', null=True),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='frames_analyzed',
            field=models.IntegerField(default=0, help_text='Number of frames analyzed'),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the job'),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='processing_fps',
            field=models.FloatField(default=0, help_text='Processing speed in FPS'),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='processing_time',
            field=models.FloatField(default=0, help_text='Total processing time in seconds'),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='When processing started', null=True),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='total_frames',
            field=models.IntegerField(default=0, help_text='Total frames in video'),
        ),
        migrations.AddField(
            model_name='videofile',
            name='camera_id',
            field=models.CharField(default='unknown', help_text='Camera identifier', max_length=100),
        ),
        migrations.AddField(
            model_name='videofile',
            name='duration',
            field=models.FloatField(default=0, help_text='Video duration in seconds'),
        ),
        migrations.AddField(
            model_name='videofile',
            name='fps',
            field=models.FloatField(default=30, help_text='Frames per second'),
        ),
        migrations.AddField(
            model_name='videofile',
            name='location',
            field=models.CharField(blank=True, help_text='Camera location description', max_length=200),
        ),
        migrations.AddField(
            model_name='videofile',
            name='recorded_at',
            field=models.DateTimeField(blank=True, help_text='When video was recorded', null=True),
        ),
        migrations.AddField(
            model_name='videofile',
            name='resolution',
            field=models.CharField(blank=True, help_text='Video resolution (e.g., 1920x1080)', max_length=20),
        ),
        migrations.AddField(
            model_name='videofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='acknowledged_by',
            field=models.CharField(blank=True, default=django.utils.timezone.now, help_text='Who acknowledged the alert', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('spillage', 'Spillage'), ('edge_damage', 'Edge Damage'), ('alignment', 'Alignment'), ('speed', 'Speed'), ('vibration', 'Vibration'), ('belt_not_found', 'Belt Not Found'), ('camera_issue', 'Camera Issue'), ('system', 'System'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='camera_id',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='alert',
            name='details',
            field=models.JSONField(blank=True, default=dict, help_text='Additional alert details'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='message',
            field=models.TextField(help_text='Detailed alert message'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10),
        ),
        migrations.AlterField(
            model_name='alert',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='camera_id',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='job_id',
            field=models.CharField(help_text='User-friendly job identifier', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='progress',
            field=models.FloatField(default=0, help_text='Processing progress (0-100)'),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='result',
            field=models.JSONField(blank=True, help_text='Processing results and metrics', null=True),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error'), ('stopped', 'Stopped'), ('paused', 'Paused')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='vision.videofile'),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='filename',
            field=models.CharField(help_text='Original filename', max_length=255),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='path',
            field=models.CharField(help_text='Full path to video file', max_length=500),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='size',
            field=models.BigIntegerField(default=0, help_text='File size in bytes'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['job', 'alert_type', 'severity'], name='vision_aler_job_id_8145f2_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['camera_id', 'timestamp'], name='vision_aler_camera__bb177c_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status', 'severity'], name='vision_aler_status_c31165_idx'),
        ),
        migrations.AddIndex(
            model_name='processingjob',
            index=models.Index(fields=['job_id'], name='vision_proc_job_id_f9b225_idx'),
        ),
        migrations.AddIndex(
            model_name='processingjob',
            index=models.Index(fields=['status', 'priority'], name='vision_proc_status_ad24a7_idx'),
        ),
        migrations.AddIndex(
            model_name='processingjob',
            index=models.Index(fields=['camera_id', 'created_at'], name='vision_proc_camera__b8ab50_idx'),
        ),
        migrations.AddIndex(
            model_name='videofile',
            index=models.Index(fields=['camera_id', 'recorded_at'], name='vision_vide_camera__13d18c_idx'),
        ),
        migrations.AddIndex(
            model_name='videofile',
            index=models.Index(fields=['filename'], name='vision_vide_filenam_4c472b_idx'),
        ),
        migrations.AlterModelTable(
            name='alert',
            table=None,
        ),
        migrations.AlterModelTable(
            name='processingjob',
            table=None,
        ),
        migrations.AlterModelTable(
            name='videofile',
            table=None,
        ),
        migrations.AddField(
            model_name='processinghistory',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='vision.processingjob'),
        ),
        migrations.DeleteModel(
            name='BeltCalibration',
        ),
        migrations.DeleteModel(
            name='BeltMetrics',
        ),
        migrations.DeleteModel(
            name='ReplayBuffer',
        ),
        migrations.AddIndex(
            model_name='processinghistory',
            index=models.Index(fields=['job', 'frame_number'], name='vision_proc_job_id_383163_idx'),
        ),
        migrations.AddIndex(
            model_name='processinghistory',
            index=models.Index(fields=['timestamp'], name='vision_proc_timesta_b17f81_idx'),
        ),
        migrations.AddIndex(
            model_name='processinghistory',
            index=models.Index(fields=['has_spillage_alert', 'has_edge_damage_alert'], name='vision_proc_has_spi_e83057_idx'),
        ),
    ]
